metadata-files:
  - _core/metadata.yml

website:
  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - section: "PSYC411"
        contents: 
          - auto: PSYC411/part1/*
          - auto: PSYC411/part2/*
      - section: "PSYC412"
        contents: 
          - auto: PSYC412/part1/*
          - auto: PSYC412/part2/*
  
format:
  html: 
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search MSc";};</script>
  