metadata-files:
  - _core/metadata.yml

website:
  sidebar:
    style: "floating"
    collapse-level: 2
    contents:
      - section: "PSYC7142"
        contents: 
          - auto: PSYC7142/part1/*
          - auto: PSYC7142/part2/*
      - section: "PSYC7143"
        contents: 
          - auto: PSYC7143/*
      - section: "PSYC7242"
        contents: 
          - auto: PSYC7242/part1/*
          - auto: PSYC7242/part2/*
format:
  html: 
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Search MSc";};</script>
  
