metadata-files:
  - _core/metadata.yml

website:
  sidebar:
    style: "floating"
    collapse-level: 1
    contents:
      - section: "PSYC401"
        contents: 
          - auto: PSYC401/part2/*
      - section: "PSYC402"
        contents: 
          - auto: PSYC402/part1/*
          - auto: PSYC402/part2/*