---
title: Week 00. Writing reproducible reports using Quarto
subtitle: Written by Rob Davies
order: 12
bibliography: references.bib
csl: psychological-bulletin.csl
---

# Writing reproducible reports using Quarto {#sec-quarto-overview}

```{r}
#| label: get-libraries
#| echo: false
#| message: false
#| warning: false

# get libraries
library(bayesplot)
library(brms)
library(broom.mixed)
library(corrplot)
library(dotwhisker)
library(GGally)
library(ggcorrplot)
library(ggdist)
library(grateful)
library(gt)
library(here)
library(kableExtra)
library(patchwork)
library(psych)
library(tidybayes)
library(tidyverse)
```

## What is this? {#sec-quarto-overview-what}

I am sharing materials here to support the development of skills in producing reproducible reports using Quarto.

These materials should provide a quick entry to the what, why and how.

You can write in Quarto, in R-Studio (or any code editor), to produce:

- reports or manuscripts;
- presentations;
- books;
- webpages.

Here, we are going to focus on reports that will be output as `.docx`.

### Related materials {#sec-quarto-overview-related}

Quarto was developed by Posit (formerly: R-Studio).

::: callout-tip
You can find the Posit guide to Quarto here:

<https://quarto.org/docs/get-started/hello/rstudio.html>
:::

### Pre-requisites {#sec-quarto-overview-pre-requisites}

1. Before you get started, you will need a local installation of R and R-Studio.

- Install R first, following the instructions here:

<https://cran.r-project.org/>

- Then install R, see:

<https://posit.co/download/rstudio-desktop/>

You need to do the installation in that order because R-Studio is the interface (an *Interactive Development Editor (IDE)*) but R does the work.

2. It is probably worth your time having a skim of the "hello world" quick start guide:

<https://quarto.org/docs/get-started/hello/rstudio.html>

## Motivations: why bother? {#sec-quarto-overview-why}

There are at least the following justifications for investing time in this (in no particular order):

1. Reproducible manuscripts: create documents that incorporate text, computation or plotting code, and bibliographic information in one place so that you can avoid the risks of the standard workflow:

- Risks: lose track of what data underlie which calculations or plots or table summaries.

2. Automate the boring stuff: figure, table or section cross-referencing; producing documents in different formats; generating bibliographies.

3. Make manuscripts or presentations or notes share-able: Quarto is free so removes barrier to entry presented by licensed software like MS Word.

4. Make nice things: plots and tables will look better.






























### References

::: {#refs}
:::